apiVersion: v1
kind: Service
metadata:
  name: toapp-service-demo
spec:
  selector:
    app: toapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toapp
spec:
  selector:
    matchLabels:
      app: toapp
  replicas:  
  template:
    metadata:
      labels:
        app: toapp
    spec:
      containers:
      - name: toapp
        #image: movista/toapp:D.1.1.0
        image: movista/randaprd:01.24.24.D01 
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
